finalize the staging environment, continuous deployment flow and spark chart

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,8 +1,22 @@
 language: bash
 sudo: required
 env:
-- K8S_CONTINUOUS_DEPLOYMENT=true
+  matrix:
+  - DEPLOY_ENVIRONMENT=staging
 services:
 - docker
 script:
-- ./continuous_deployment.sh
+- |
+  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] &&\
+     [ "${TRAVIS_COMMIT_MESSAGE}" != "" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy && [ "${TRAVIS_COMMIT}" != "" ]
+  then
+      openssl aes-256-cbc -K $encrypted_de69cc520442_key -iv $encrypted_de69cc520442_iv -in midburn-k8s-ops.json.enc -out secret-midburn-k8s-ops.json -d
+      IMAGE_TAG="gcr.io/uumpa123/midburn-k8s:${TRAVIS_COMMIT}"
+      B64_UPDATE_VALUES=`echo '{"global":{"opsImage":"'${IMAGE_TAG}'"}}' | base64 -w0`
+      ./run_docker_ops.sh "${DEPLOY_ENVIRONMENT}" "
+           cd /ops
+           ! ./helm_upgrade.sh \
+                 && echo 'failed helm upgrade' && exit 1
+           exit 0
+      "
+  fi
