.travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,21 +2,27 @@ language: bash
 sudo: required
 env:
   matrix:
-  - DEPLOY_ENVIRONMENT=staging
+  - DEPLOY_ENVIRONMENT=staging DEPLOY_BRANCH=master
+  - DEPLOY_ENVIRONMENT=production DEPLOY_BRANCH=master
 services:
 - docker
 script:
 - |
-  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] &&\
+  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "${DEPLOY_BRANCH}" ] &&\
      [ "${TRAVIS_COMMIT_MESSAGE}" != "" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy && [ "${TRAVIS_COMMIT}" != "" ]
   then
-      openssl aes-256-cbc -K $encrypted_de69cc520442_key -iv $encrypted_de69cc520442_iv -in midburn-k8s-ops.json.enc -out secret-midburn-k8s-ops.json -d
-      IMAGE_TAG="gcr.io/uumpa123/midburn-k8s:${TRAVIS_COMMIT}"
-      B64_UPDATE_VALUES=`echo '{"global":{"opsImage":"'${IMAGE_TAG}'"}}' | base64 -w0`
-      ./run_docker_ops.sh "${DEPLOY_ENVIRONMENT}" "
-           cd /ops
-           ! ./helm_upgrade.sh \
-                 && echo 'failed helm upgrade' && exit 1
-           exit 0
-      "
+      openssl aes-256-cbc -K $encrypted_de69cc520442_key -iv $encrypted_de69cc520442_iv -in ./k8s-ops-secret.json.enc -out secret-k8s-ops.json -d
+      K8S_ENVIRONMENT_NAME="${DEPLOY_ENVIRONMENT}"
+      OPS_REPO_SLUG="Midburn/midburn-k8s"
+      OPS_REPO_BRANCH="${DEPLOY_BRANCH}"
+      wget https://raw.githubusercontent.com/OriHoch/sk8s-ops/master/run_docker_ops.sh
+      chmod +x run_docker_ops.sh
+      ! ./run_docker_ops.sh "${K8S_ENVIRONMENT_NAME}" "
+         RES=0
+         ! ./helm_upgrade.sh && echo "failed helm upgrade" && RES=1;
+         ! ./helm_upgrade_external_chart.sh spark && echo "failed spark upgrade" && RES=1;
+         ! ./helm_upgrade_external_chart.sh volunteers && echo "failed volunteers upgrade" && RES=1;
+         exit "'$'"RES
+      " "orihoch/sk8s-ops" "${OPS_REPO_SLUG}" "${OPS_REPO_BRANCH}" "" "-v `pwd`:/volunteers" \
+          && echo 'failed to run docker ops' && exit 1
   fi
